services:
  dracor-sandbox:
    image: "dracor/dracor-sandbox"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dracor-sandbox
    privileged: true
    environment:
      - GITHUB_TOKEN
    ports:
      - "8088:8088"
      - "8888:8888"
    volumes:
      - ./export:/home/dracor/notebooks/export
      - ./import:/home/dracor/notebooks/import