services:
  dracor-builder:
    image: "dracor/dracor-builder"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dracor-builder
    privileged: true
    environment:
      - GITHUB_TOKEN
    ports:
      - "8088:8088"
      - "8888:8888"
    volumes:
      - ./export:/home/dracor/notebooks/export
      - ./import:/home/dracor/notebooks/import