# Stable DraCor System 'vebidracor'
services:
  api:
    depends_on:
    - triplestore
    - metrics
    environment:
    - DRACOR_API_BASE=http://localhost:8088/api
    - EXIST_PASSWORD =
    image: dracor/stable-dracor:vebidracor_v4_arm64
    ports:
    - 8080:8080
  frontend:
    depends_on:
    - api
    environment:
    - DRACOR_API=http://api:8080/exist/restxq
    image: dracor/dracor-frontend:v1.6.0-dirty
    ports:
    - 8088:80
  metrics:
    image: dracor/dracor-metrics:v1.2.0
    ports:
    - 8030:8030
  triplestore:
    environment:
    - ADMIN_PASSWORD=qwerty
    image: dracor/dracor-fuseki:v1.0.0
    ports:
    - 3030:3030
